<?php

namespace app\home\controller;


use app\home\model\BuycarModel;
use think\Controller;
use think\Db;
use think\Request;

class Buycar extends Base{


    protected $userId;


    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->userId = session('uid');
    }


    /**
     * 加入购物车
     */
    public function addcart(Request $request){
        $goodId = $request->param('goodId');
        if(empty($goodId)){
            return json(['msg'=>'参数失败','code'=>1001]);
        }
        $num = $request->param('num')?:1;
        $buycar = Db::table('buycar')->where(['user_id'=>$this->userId,'good_id'=>$goodId])->find();
        if($buycar){
            $buycar['good_num'] += $num;
            $res = Db::table('buycar')->update($buycar);
        }else{
            $data = [];
            $data['user_id'] = $this->userId;
            $data['good_id'] = $goodId;
            $data['good_num'] = $num;
            $data['created_at'] = time();
            $res = Db::table('buycar')->insert($data);
        }
        if($res){
            return json(['msg'=>'加入购物车成功','code'=>200]);
        }
        return json(['msg'=>'加入购物车失败','code'=>1002]);
    }


    /**
     * @return \think\response\Json
     * 购物车列表
     */
    public function cartList(){
        $buycar = BuycarModel::all(['user_id'=>$this->userId]);
        $return = [];
        foreach($buycar as $key=>$val){
            $return[$key]['id'] = $val['good_id'];
            $return[$key]['goodName'] = $val['good']['name'];
            $return[$key]['goodImg'] = $val['good']['img'];
            $return[$key]['goodPrice'] = $val['good']['price'];
            $return[$key]['goodNum'] = $val['good_num'];
        }
        return json(['data'=>$return,'msg'=>'查询成功','code'=>200]);
    }


    /**
     * @param Request $request
     * @return \think\response\Json
     * @throws \think\Exception
     * 编辑购物车
     */
    public function editCart(Request $request){
        $goodId = $request->param('goodId');
        $goodNum = $request->param('goodNum');
        $goodId = explode(',',rtrim($goodId,','));
        $res = [];
        foreach($goodId as $key=>$val){
            $res = Db::table('buycar')->where(['user_id'=>$this->userId,'good_id'=>$val])->update(['good_num'=>$goodNum]);
        }
        if($res){
            return json(['msg'=>'编辑成功','code'=>200]);
        }
        return json(['msg'=>'编辑失败','code'=>1001]);
    }

    /**
     * @param Request $request
     * @return \think\response\Json
     * @throws \think\Exception
     * 删除购物车
     */
    public function delCart(Request $request){
        $goodId = $request->param('goodId');
        $goodId = explode(',',rtrim($goodId,','));
        $res = [];
        foreach($goodId as $key=>$val){
            $res = Db::table('buycar')->where(['user_id'=>$this->userId,'good_id'=>$val])->delete();
        }
        if($res){
            return json(['msg'=>'删除成功','code'=>200]);
        }
        return json(['msg'=>'删除失败','code'=>1001]);
    }





}
