<?php

namespace app\home\controller;


use app\admin\model\Users;
use think\Controller;
use think\Db;
use think\Exception;
use think\Request;


class Recharge extends Base{

    protected $userId;

    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->userId = session('uid');
    }


    /**
     * 我的充值卡
     */
    public function index(){
        $user = Users::get($this->userId);
        $record = Db::table('recharge_record')->where('user_id',$this->userId)->order('id','desc')->select();
        foreach($record as $key=>$val){
            if(empty($val['card_num'])){
                $record[$key]['card_num'] = $user['phone'];
            }
        }
        return json(['data'=>['totalMoney'=>$user['recharge_card'],'record'=>$record],'msg'=>'查询成功','code'=>200]);
    }

    /**
     * @param Request $request
     * @return \think\response\Json
     * 绑定充值卡
     * 返回充值卡号,充值卡金额
     */
    public function bindcard(Request $request){
        $input = $request->post();
        if(empty($input['card_num'])){
            return json(['msg'=>'充值卡号不能为空','code'=>1001]);
        }else if(empty($input['card_password'])){
            return json(['msg'=>'充值卡密码不能为空','code'=>1001]);
        }
        $rech = Db::table('recharge_card')
            ->where(['card_number'=>$input['card_num'],'card_password'=>$input['card_password']])
            ->find();
        if($rech['status'] != 2){
            return json(['msg'=>'充值卡未出售或已使用','code'=>1001]);
        }
        if($rech){
            Db::startTrans();
            try{
                //用户充值卡钱包增加
                Db::table('users')->where('id',$this->userId)->setInc('recharge_card',$rech['value']);
                //更新充值卡状态
                $data['user_id'] = $this->userId;
                $data['status'] = 3;
                $data['use_time'] = date('YmdHis');
                Db::table('reachrge_card')->where('id',$rech['id'])->update($data);
                //增加记录
                $record['user_id'] = $this->userId;
                $record['card_num'] = $rech['card_number'];
                $record['money'] = $rech['value'];
                $record['remark'] = '充值卡充值';
                Db::table('recharge_record')->insert($record);
                //提交
                Db::commit();
                return json(['data'=>['code'=>$rech['card_number'],'money'=>$rech['value']],'msg'=>'充值成功','code'=>200]);
            }catch(Exception $e){
                Db::rollback();
                return json(['msg'=>'充值失败','code'=>1002]);
            }
        }
        return json(['msg'=>'充值卡不存在','code'=>1002]);
    }



}
